name: Build Windows Installer

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g. 0.0.0-alpha)'
        required: true

jobs:
  build-windows-installer:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller app.py --name Bookkeeppr --windowed --onefile --icon=assets/bookkeeppr.ico

      - name: Download and install Inno Setup
        run: |
          Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile ".\is.exe"
          Start-Process ".\is.exe" -ArgumentList "/VERYSILENT /NORESTART" -Wait

      - name: Extract version and update .iss
        run: |
          $version = if ($env:GITHUB_EVENT_NAME -eq 'workflow_dispatch') { "${{ github.event.inputs.version }}" } else { "${{ github.ref_name }}".TrimStart('v') }
          (Get-Content installer\BookkeepprInstaller.iss) -replace 'AppVersion=.*', "AppVersion=$version" | Set-Content installer\BookkeepprInstaller.iss

      - name: Compile installer with Inno Setup
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installer\BookkeepprInstaller.iss"

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          files: dist/BookkeepprInstaller.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
