name: Build Windows Installer

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows-installer:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller app.py --name Bookkeeppr --windowed --onefile --icon=assets/bookkeeppr.ico

      - name: Download and install Inno Setup
        run: |
          Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile ".\is.exe"
          Start-Process ".\is.exe" -ArgumentList "/VERYSILENT /NORESTART" -Wait

      - name: Extract version from tag and update .iss
        run: |
          $version = "${{ github.ref_name }}".TrimStart('v')
          (Get-Content installer\BookkeepprInstaller.iss) -replace 'AppVersion=.*', "AppVersion=$version" | Set-Content installer\BookkeepprInstaller.iss

      - name: Compile installer with Inno Setup
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer\BookkeepprInstaller.iss

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: dist/BookkeepprInstaller.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
