name: Manual Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Version tag (e.g. v1.0.0)"
        required: true

jobs:
  create-release-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create Git tag and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ github.event.inputs.tag_name }}
          git push origin ${{ github.event.inputs.tag_name }}

      - name: Trigger Windows installer workflow manually
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-windows-installer.yml
          token: ${{ secrets.GH_PAT_TRIGGER }}
          inputs: '{ "version": "${{ github.event.inputs.tag_name }}" }'